;; *Exercise 1.9:* Each of the following two procedures defines a
;; method for adding two positive integers in terms of the procedures
;; `inc', which increments its argument by 1, and `dec', which
;; decrements its argument by 1.

;;      (define (+ a b)
;;        (if (= a 0)
;;            b
;;            (inc (+ (dec a) b))))

;;      (define (+ a b)
;;        (if (= a 0)
;;            b
;;            (+ (dec a) (inc b))))

;; Using the substitution model, illustrate the process generated by
;; each procedure in evaluating `(+ 4 5)'.  Are these processes
;; iterative or recursive?


(defun inc (x)
  (+ x 1))

(defun dec (x)
  (- x 1))

(defun plus (a b)
  "Recursive process:
   (plus 4 5)
   (inc (plus 3 5))
   (inc (inc (plus 2 5)))
   (inc (inc (inc (plus 1 5))))
   (inc (inc (inc (inc (plus 0 5)))))
   (inc (inc (inc (inc 5))))
   (inc (inc (inc 6)))
   (inc (inc 7))
   (inc 8)
   9"
  (if (= a 0)
      b
    (inc (plus (dec a) b))))

(defun plus (a b)
  "Iterative process:
   (plus 4 5)
   (plus 3 6)
   (plus 2 7)
   (plus 1 8)
   (plus 0 9)
   9"
  (if (= a 0)
      b
    (plus (dec a) (inc b))))
